#ifndef CONFIG_H

#define CONFIG_H

#include <stdint.h>

#define PIN_OLED_SDA 6
#define PIN_OLED_SCL 7 

#define PIN_SWITCH 1

#define PIN_ENCODER_A 26
#define PIN_ENCODER_B 28
#define PIN_ENCODER_SW 27

#define I2C_PORT i2c0
#define I2C_BAUDRATE 400000
#define OLED_I2C_ADDR 0x3C

#define OLED_WIDTH 128
#define OLED_HEIGHT 32
#define OLED_PAGES (OLED_HEIGHT / 8)
#define OLED_BUFFER_SIZE (OLED_WIDTH * OLED_PAGES)

#define FONT_WIDTH 6
#define FONT_HEIGHT 8
#define CHARS_PER_LINE (OLED_WIDTH / FONT_WIDTH)
#define LINES_PER_SCREEN (OLED_HEIGHT / FONT_HEIGHT)

#define TIMING_SWITCH_DEBOUNCE_MS 10
#define TIMING_ENCODER_DEBOUNCE_MS 2
#define TIMING_LONG_PRESS_MS 800
#define TIMING_DOUBLE_PRESS_WINDOW_MS 300


#endif