#ifndef CONFIG_H

#define CONFIG_H

#include <stdint.h>

#define PIN_OLED_SDA 6
#define PIN_OLED_SCL 7 

#define PIN_SWITCH 1

#define PIN_ENCODER_A 26
#define PIN_ENCODER_B 28
#define PIN_ENCODER_SW 27

#define I2C_PORT i2c0
#define I2C_BAUDRATE 400000
#define OLED_I2C_ADDR 0x3C

#define OLED_WIDTH 128
#define OLED_HEIGHT 32
#define OLED_PAGES (OLED_HEIGHT / 8)
#define OLED_BUFFER_SIZE (OLED_WIDTH * OLED_PAGES)

#define FONT_WIDTH 6
#define FONT_HEIGHT 8
#define CHARS_PER_LINE (OLED_WIDTH / FONT_WIDTH)
#define LINES_PER_SCREEN (OLED_HEIGHT / FONT_HEIGHT)

#define TIMING_SWITCH_DEBOUNCE_MS 10
#define TIMING_ENCODER_DEBOUNCE_MS 2
#define TIMING_LONG_PRESS_MS 800
#define TIMING_DOUBLE_PRESS_WINDOW_MS 300

#define TIMING_CHAR_DELAY_DEFULT_MS 2
#define TIMING_CHAR_DELAY_MIN_MIS 1
#define TIMING_CHAR_DELAY_MAX_MS 50

#define TIMING_DISPLAY_REFRESH_MS 33
#define TIMING_INPUT_POLL_MS 1
#define TIMING_IDLE_TIMEOUT_MS 10000

#define MAX_PROCEDURES 16
#define MAX_NAME_LENGTH 32
#define MAX_PAYLOAD_SIZE 65535 // this is the max of uint16

#define PROCEDURE_HEADER_SIZE 256
#define PROCEDURE_MAGIC 0x54584449
#define PROCEDURE_VERSION 1

#define FLASH_PROCEDURE_INDEX 0x10020000
#define FLASH_PROCEDURE_DATA 0x10021000
#define FLASH_PAYLOAD_SLOT_SIZE 0x10000


#define USB_VID 0xCAFE
#define USB_PID 0x4004

#define USB_MANUFACTURER "arya"
#define USB_PRODUCT "not malware"

#define PROCEDURE_FLAG_VALID (1<<0)
#define PROCEDURE_FLAG_CONFIRM_REQUIRED (1<<1)

#endif